### PR TITLE
Fix admin grid quirks

### LINKED ISSUE #58: Admin grid shows only data of last record
When I open the grid of attribute landing pages, only data is shown from the last record. When I use a filter on ID (for example), the correct data is shown. However, when I remove the filter, again only the data from the last record is shown.

Module is version 4.0.0 on PHP8.1 with Magento Commerce 2.4.5-p1.

Screenshot_2022-11-21_at_14_04_00

I moved from `tweakwise/magento2-attributelanding` to `emico/m2-attributelanding` like suggested in https://github.com/Tweakwise/Magento2AttributeLanding/issues/5 which doesn't seem to resolve the issue.

### PR DESCRIPTION
**Pull request by ahuininga-orisha**
Fixes #58 

Is an issue with magento 2.4.5.

### CODE REVIEW

**Comment by bramstroker** [comment]
Nice one @ah-net. Client of us also reported this issue, was just about to dive into this, but you already fixed it. Great!
Is this BC with Magento versions earlier than 2.4.5?

**Comment by ah-net** [comment]
@bramstroker Tested on magento 2.4.3, no problems

**Comment by bramstroker** [comment]
Ok great thanks for verifying.

**Review by bramstroker — APPROVED** [review]

**Comment by bramstroker** [comment]
Can confirm it's also fixed for our client.
Just made a new release v4.0.2

**Pull request merged**
